# Generated by Django 6.0 on 2026-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('short_intro', models.TextField(help_text='A brief 1-2 sentence intro')),
                ('description', models.TextField(help_text='Full detailed description')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
