# Generated by Django 6.0 on 2026-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_alter_hero_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.PositiveSmallIntegerField(default=50, help_text='Proficiency % (0-100)')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='social_profiles',
            field=models.ManyToManyField(blank=True, to='main.socialprofile'),
        ),
        migrations.AddField(
            model_name='about',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='main.hobby'),
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.ManyToManyField(blank=True, to='main.language'),
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(blank=True, to='main.skill'),
        ),
    ]
